spring:
  profiles: real
  #resources:
    #static-locations: file:///${custom.adCheck.imgPath}
  datasource: 
    url: jdbc:mariadb://121.169.194.198:3306/spring
    username: planty
    password: 'Planty2020' #숫자인 경우 인식이 잘 안 될 수 있음. 이 경우 '' 로 둘러 싸야 함
    driverClassName: org.mariadb.jdbc.Driver
    #dbcp2 https://www.mkyong.com/spring-boot/spring-boot-jdbc-oracle-database-commons-dbcp2-example/
    #type: org.apache.commons.dbcp2.BasicDataSource 
    #dbcp2:
      #max-total: 20
      #max-idle: 20
      #validation-query: select 1
      #test-on-borrow: false
      #test-while-idle: true
      #time-between-eviction-runs-millis: 600000
      #num-tests-per-eviction-run: 7
      #min-evictable-idle-time-millis: -1
    #hikari (type은 굳이 지정할 필요 없음)
    #type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 5000 #30000ms 클라이언트가 pool에 Connection을 요청하는데 기다리는 최대시간 설정
      #maxLifetime: 1800000 #1800000ms(30분) Coneection의 최대 유지 시간 설정 ,시간이 지나면 connection은 작업이 완료되면 폐기됨 하지만 유휴 거낵션은 바로 폐기됨
      maximumPoolSize: 20 #기본 10  유휴 및 사용중인 Connection을 포함하여 풀에 보관가능한 최대 connection 개수를 설정
      validationTimeout: 1000 #5000ms, connectionTimeout 보다 적어야 함
      #minimumldle: 10 #기본 10 Connection pool에서 유지가능한 최소 커낵션 개수를 설정 
      #idleTimeout: 60000 기본 (60000 (10분)) Connection pool에서 유휴 상태로 유지시킬 최대시간을 설정
      #readyOnly: false (default: false) pool에서 얻은 connection이 기본적으로 readOnly인지 지정하는 설정 데이터베이스가 readOnly 속성을 지원할 경우에만 사용 가능
#JMX는 실행 중인 애플리케이션의 상태를 모니터링 하고, 설정을 변경할 수 있게 해주는 API
  jmx: 
    enabled: false
  devtools:
    livereload:
      enabled: false
#정적인 내용도 자동 리로딩 되게 하기 위해 devtools에서 별도의 서버(port 35729)를 실행해서 
#브라우저와 연동함(브라우저 플러그인과 통신)
#필요 없으면 위에처럼 꺼야 함
---
server:
  port: 8080
---
custom:
  # 1시간에 한번  '0 0 0/1 * * ?'
  #1분마다
  schedule: '0 0/1 * * * ?'